name: Build Python Image

on: [ push ]

jobs:
  build:
    name: Build Image
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker
        run: |
          docker build . -t python-docker
          docker login -u chenglin0 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag python-docker:latest limingxinleo/python-docker:latest
          docker push limingxinleo/python-docker:latest
